### ISSUE TITLE
other lists

### ISSUE THREAD

**Issue by tomByrer** [defeatcovid19/awesome-covid19-resources#1]
Hi, cool you want to help spread information, but there are already a few lists going:

The best
https://github.com/soroushchehresa/awesome-coronavirus

Short list
https://github.com/fnielsen/awesome-covid-19-resources

Projects, mostly AI/ML
https://github.com/jbn/COVID-19

Things to do when stuck at home.
https://github.com/adamdriscoll/awesome-covid19-resources

**Comment by mrtj** [comment]
Thank you, we'll review these list as well! This list aims to collect the official outbreak time series, medical imaging datasets and other resources to support the work at [defeatcovid19.org](https://www.defeatcovid19.org).

**Comment by tomByrer** [comment]
Great, there are likely already those sources listed in the above repos, ether directly, or indirectly (eg follow the links for API, then that repo will link their sources).

**Comment by Andrea922** [comment]
http://covid-live.it

Monitoring Italian data
