### ISSUE TITLE
Project for tracking people without privacy issues

### ISSUE THREAD

**Issue by trane77** [defeatcovid19/awesome-covid19-resources#13]
Hello,

I'd like to link my repository in your page, as I think that there are a lot of different 
projects out there nearly identical.. I think that this repository is the right place to keep things organized, so if you want, here's the repository link: [covid-19-google-gps-tracking](https://github.com/f-ricchiuto/covid-19-google-gps-tracking).

Unfortunately I cannot work on it but I think that the idea is ok, especially regarding the privacy concerns.

(It's incredible that people is giving more attention to privacy than their lives)

**Comment by mrtj** [comment]
Hi, please read or [Contribution Guidelines](https://github.com/defeatcovid19/awesome-covid19-resources/blob/master/contributing.md) and if you feel your submission fits in, you're more than welcome to open a PR for adding new links.
