### ISSUE TITLE
Idea: Scanning and crosslinking of components with publication data

### ISSUE THREAD

**Issue by redknightlois** [defeatcovid19/awesome-covid19-resources#4]
I am thinking that it would be a good idea to try to search for specific drugs shown to work on the computational model of the ACE2 on the relevant literature as an aggregation to the articles dataset. The list can be found in the supplementary information of "Repurposing Therapeutics for COVID-19: Supercomputer-Based Docking to the SARS-CoV-2 Viral Spike Protein and Viral Spike Protein-Human ACE2 Interface" https://chemrxiv.org/articles/Repurposing_Therapeutics_for_the_Wuhan_Coronavirus_nCov-2019_Supercomputer-Based_Docking_to_the_Viral_S_Protein_and_Human_ACE2_Interface/11871402/4

If we could allow medical researchers to spot supporting literature for all the relevant higher score components, they could create experimental protocols like the one suggested (and now approved on the USA) from the french researchers: "Hydroxychloroquine and azithromycin as a treatment of COVID-19: results of an open-label non-randomized clinical trial" https://drive.google.com/file/d/186Bel9RqfsmEx55FDum4xY_IlWSHnGbj/view

There is a need to cleanup the data and figure out how to visualize and crosslink the relevant publications. The good thing about this one, is that the data is already out there from the Kaggle dataset and the published article. 

For example the compound used by the French can be found with a VINA Score of -5.6 where are a few that have even better results binding to ACE2.
![image](https://user-images.githubusercontent.com/1045411/77108991-f10e9e00-6a01-11ea-88a4-3261da3e4a6a.png)

**Comment by mrtj** [comment]
Hello, now we opened another repository for the project organization that might be more suitable for submitting these ideas. Could you please re-create this issue there? There is already a proposal for "Drug impact analysis and simulation" track, you could even candidate as a coordinator of that track! https://github.com/defeatcovid19/defeatcovid19-project
